apiVersion: v1
kind: Secret 
metadata:
  name: frontend-secret
  namespace: tmb13fe
type: Opaque
data:
  REACT_APP_BACKEND_URL: aHR0cDovL2JhY2tlbmQtc2VydmljZS50bWIxM2JlLnN2Yy5jbHVzdGVyLmxvY2FsOjMwMDE=
  # http://backend-service.tmb13be.svc.cluster.local:3001