apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: tmb13fe
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30086